[project]
dynamic = ["dependencies"]
name = "KTANE-Agent"
version = "1.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
